[build]
rustflags = ["-C", "target-cpu=native"]

# Using lld as the linker greatly improves compilation time.
# Since Rust 1.90 lld is the default linker on x86_64-unknown-linux-gnu
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-args=-fuse-ld=lld"]
[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-args=-fuse-ld=lld"]
[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-args=-fuse-ld=lld"]
